Source/Forum/Forum.WEB/Models/Topic/ResponseOnAddNewTopic.cs
namespace Forum.WEB.Models.Topic
{
    public class ResponseOnAddNewTopic
    {
        public bool Result { get; set; }
        public string mainError { get; set; }
        public string errorName { get; set; }
        public string errorDesription { get; set; }
    }
}

Source/Forum/Forum.WEB/Models/Topic/ResponseOnEditTopicData.cs
namespace Forum.WEB.Models.Topic
{
    public class ResponseOnEditTopicData
    {
        public bool Result { get; set; }
        public string ErrorName { get; set; }
        public string ErrorDescription { get; set; }
        public string MainError { get; set; }
    }
}

Source/Forum/Forum.WEB/Models/Topic/ResponseOnSendMessage.cs
namespace Forum.WEB.Models.Topic
{
    public class ResponseOnSendMessage
    {
        public bool Result { get; set; }
        public string Error { get; set; }
    }
}

Source/Forum/Forum.WEB/Models/Topic/TopicViewModel.cs
using Forum.BLL.DTO;
using System.Collections.Generic;

namespace Forum.WEB.Models.Topic
{
    public class TopicViewModel
    {
        public TopicDTO Topic { get; set; }
        public IEnumerable<MessageDTO> Messages { get; set; }
    }
}

Source/Forum/Forum.WEB/Controllers/TopicController.cs
using Forum.BLL.Interfaces;
using Forum.WEB.Models.Topic;
using Microsoft.Owin.Security;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Forum.WEB.Controllers
{
    public class TopicController : Controller
    {
        private IUserService UserService;

        public TopicController(IUserService serv)
        {
            UserService = serv;
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        public async Task<ActionResult> Index()
        {
            var res = await UserService.GetAllTopics();
            return View(res);
        }

        [HttpPost]
        public async Task<JsonResult> AddTopic(string name,string description)
        {
            var resValidName = CheckValidateString(name, new Regex(@"^(?=.*[А-яA-z0-9]).{4,15}$"));
            var resValidDescription = CheckValidateString(description, new Regex(@"^(?=.*[А-яA-z0-9]).{8,40}$"));
            if(resValidName && resValidDescription)
            {
                var res = await UserService.CreateTopic(new BLL.DTO.TopicDTO { Name = name, Description = description });
                if (res.Succedeed)
                {
                    return Json(new ResponseOnAddNewTopic { Result = true }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new ResponseOnAddNewTopic { Result = false, mainError = res.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                 var r = new ResponseOnAddNewTopic
                 {
                     Result = false,
                     errorName = resValidName ? "" : "Name must contain at least 4 characters and less than 15",
                     errorDesription = resValidDescription ? "" : "Description must contain at least 8 characters and less than 40"
                 };
                return Json(r, JsonRequestBehavior.AllowGet); 
            }
        }

        public bool CheckValidateString(string str,Regex reg)
        {
            return reg.IsMatch(str);
        }
        

        [HttpPost]
        public async Task RemoveTopic(int id)
        {
            await UserService.RemoveTopic(id);
        }

        [HttpPost]
        public async Task<JsonResult> EditTopicData(int id,string name,string description)
        {
            var resValidName = CheckValidateString(name, new Regex(@"^(?=.*[А-яA-z0-9]).{4,15}$"));
            var resValidDescription = CheckValidateString(description, new Regex(@"^(?=.*[А-яA-z0-9]).{8,15}$"));
            if (resValidName && resValidDescription)
            {
                var res = await UserService.EditTopic(id,name,description);
                if (res.Succedeed)
                {
                    return Json(new ResponseOnEditTopicData { Result = true }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new ResponseOnEditTopicData { Result = false, MainError = res.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                var r = new ResponseOnEditTopicData
                {
                    Result = false,
                    ErrorName = resValidName ? "" : "The name must contain at least 4 characters",
                    ErrorDescription = resValidDescription ? "" : "The description must contain at least 8 characters"
                };
                return Json(r, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public async Task DeleteMessage(int messageId)
        {
            await UserService.DeleteMessage(messageId);
        }

        [Authorize]
        public async Task<ActionResult> TopicView(int id)
        {
            var message = await UserService.GetMessagesInTopic(id);
            var topic = await UserService.GetTopicById(id);
            return View(new TopicViewModel() { Messages = message, Topic = topic });
        }

        [HttpPost]
        public async Task<JsonResult> SendMessage(string text,int topicId)
        {
            if(CheckValidateString(text, new Regex(@"^(?=.*[А-яA-z0-9]).{1,65}$")))
            {
                await UserService.SendMessageInTopic(topicId, AuthenticationManager.User.Identity.Name, text);
                return Json(new ResponseOnSendMessage { Result = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new ResponseOnSendMessage { Result = false, Error = "The message must be more than one character and less than 65 chars." }, JsonRequestBehavior.AllowGet);
            }
            
        }

        [HttpPost]
        public async Task<JsonResult> EditMessage(string idMessage, string newMessage)
        {
            if (CheckValidateString(newMessage, new Regex(@"^(?=.*[А-яA-z0-9]).{1,45}$")))
            {
                await UserService.EditMessage(int.Parse(idMessage), newMessage);
                return Json(new ResponseOnSendMessage { Result = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new ResponseOnSendMessage { Result = false, Error = "The message must be more than one character and less than 30 chars." }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Source/Forum/Forum.WEB/Views/Topic/Index.cshtml
@model List<Forum.BLL.DTO.TopicDTO>
@{
    ViewBag.Title = "Home Page";
}


@if (User.Identity.IsAuthenticated)
{
    <h2> All Categories</h2>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Description</td>
                    <td>
                        <input type="button" value="show" class="btn btn-info" onclick="location.href='@Url.Action("TopicView", "Topic", new { id = @item.Id })'" />
                        @if (@User.IsInRole("admin"))
                        {
                            <button id="BtnEdit" type="button" onclick="EditTopic(@item.Id,'@item.Name','@item.Description')" class="btn btn-warning">edit</button>
                            <button id="BtnRemove" onclick="RemoveTopic(@item.Id)" type="button" class="btn btn-danger">delete</button>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h2>After login, all categories will be shown.</h2>
}

@if (@User.IsInRole("admin"))
{
    <div class="panel panel-default">
        <div class="panel-body">Adding a new category</div>
        <div class="panel-footer">
            <label>Name</label>
            <input id="InpNameTopic" type="text" class="form-control" />
            <label id="errNewTopicName" style="color:red"></label><br />
            <label>Description</label>
            <input id="InpDescriptionTopic" type="text" class="form-control" />
            <label id="errNewTopicDesription" style="color:red"></label><br />
            <label id="errNewTopicMain" style="color:red"></label><br />
            <input id="BtnAddTopic" type="button" class="btn btn-success" value="Add" />
        </div>
    </div>

}

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="exampleModalLabel">Edit category</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <label id="inpEditTopicId" hidden></label>
                <label>Category name: </label>
                <input id="inpEditTopicName" type="text" class="form-control" />
                <label id="lblErrorTopicName" style="color:red"></label><br />
                <label>Category description: </label>
                <input id="inpEditTopicDescription" type="text" class="form-control" />
                <label id="lblErrorTopicDesciprion" style="color:red"></label> <br/>
                <label id="lblErrorTopicMain" style="color:red"></label> <br/>
                <label id="errEditMessage" style="color:red"></label><br />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" id="BtnSaveEditTopic" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/indexScript")

<script type="text/javascript">
    $(function () {
         SetUrlForAddTopic('@Url.Action("AddTopic", "Topic")');
         SetUrlForRemoveTopic('@Url.Action("RemoveTopic", "Topic")');
          SetUrlForEditTopic('@Url.Action("EditTopicData", "Topic")');
    });
</script>

Source/Forum/Forum.WEB/Views/Topic/TopicView.cshtml
@model Forum.WEB.Models.Topic.TopicViewModel

@using Forum.BLL.DTO;

@{
    ViewBag.Title = "TopicView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>@Model.Topic.Name</h4>
<h5>Description:  @Model.Topic.Description</h5>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Author</th>
            <th scope="col">Text</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Messages)
        {
            <tr>
                <td>@item.User.Name</td>
                <td>@item.Text</td>
                @if (User.Identity.Name == @item.User.Name)
                {
                    <td>
                        <button type="button" class="btn btn-warning" onclick="EditMessage(@item.Id,'@item.Text')">edit</button>
                        <button type="button" class="btn btn-danger" onclick="DeleteMessage(@item.Id)">delete</button>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>
<label id="idMessageHideLabel" hidden></label>


<div class="panel panel-default">
    <div class="panel-body">To write a message</div>
    <div class="panel-footer">
        <input id="InpText" type="text" class="form-control" />
        <label id="errSendMessage" style="color:red"></label><br />
        <input type="button" class="btn btn-success" value="Send" onclick="SendMessage(@Model.Topic.Id)" id="BtnSendMessage" />
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="exampleModalLabel">Edit message</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input id="valueForEdit" type="text" class="form-control" />
                <label id="errEditMessage" style="color:red"></label><br />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" id="BtnEditMessage" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        SetUrlForEditMessage('@Url.Action("EditMessage", "Topic")');
        SetUrlForSemdMessage('@Url.Action("SendMessage", "Topic")');
        SetUrlForDeleteMessage('@Url.Action("DeleteMessage", "Topic")');
    });
</script>


@Scripts.Render("~/bundles/topicViewScript")